name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
        working-directory: .
    steps:
    - uses: actions/checkout@v2
#     - uses: ilammy/msvc-dev-cmd@v1
#     - name: compile
#       run: |
#         cl /c main.c /Fo:main.obj
#         link main.obj /OUT:main.exe
#         main.exe
#         dir
#     - uses: egor-tensin/setup-mingw@v2
#       with:
#         platform: x64
#     - name: compile 2
#       run: |
#         gcc -c main.c -o main.o
#         gcc main.o -o main.exe
#         main.exe
#         dir
#         mingw32-make --help
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw32
        update: true
        install: mingw-w64-i686-make
    - name: compile x86
      run: |
        gcc -c main.c -o main.o
        gcc main.o -o main.exe
        main.exe
        dir
        mingw32-make --help
